//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B_Majozi_Practical_Assignment.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUser", ReplyAction="http://tempuri.org/IService1/getUserResponse")]
        string getUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUser", ReplyAction="http://tempuri.org/IService1/getUserResponse")]
        System.Threading.Tasks.Task<string> getUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserName", ReplyAction="http://tempuri.org/IService1/getUserNameResponse")]
        string getUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserName", ReplyAction="http://tempuri.org/IService1/getUserNameResponse")]
        System.Threading.Tasks.Task<string> getUserNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserEmail", ReplyAction="http://tempuri.org/IService1/getUserEmailResponse")]
        string getUserEmail(string userEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserEmail", ReplyAction="http://tempuri.org/IService1/getUserEmailResponse")]
        System.Threading.Tasks.Task<string> getUserEmailAsync(string userEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDateofB", ReplyAction="http://tempuri.org/IService1/getDateofBResponse")]
        System.DateTime getDateofB(System.DateTime dateofB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDateofB", ReplyAction="http://tempuri.org/IService1/getDateofBResponse")]
        System.Threading.Tasks.Task<System.DateTime> getDateofBAsync(System.DateTime dateofB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getContact", ReplyAction="http://tempuri.org/IService1/getContactResponse")]
        string getContact(string ContactNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getContact", ReplyAction="http://tempuri.org/IService1/getContactResponse")]
        System.Threading.Tasks.Task<string> getContactAsync(string ContactNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setUser", ReplyAction="http://tempuri.org/IService1/setUserResponse")]
        string setUser(string userName, string userEmai, System.DateTime dateofB, string ContactNum, bool pizza, bool past, bool papwor, bool other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setUser", ReplyAction="http://tempuri.org/IService1/setUserResponse")]
        System.Threading.Tasks.Task<string> setUserAsync(string userName, string userEmai, System.DateTime dateofB, string ContactNum, bool pizza, bool past, bool papwor, bool other);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : B_Majozi_Practical_Assignment.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<B_Majozi_Practical_Assignment.ServiceReference1.IService1>, B_Majozi_Practical_Assignment.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getUser(int userId) {
            return base.Channel.getUser(userId);
        }
        
        public System.Threading.Tasks.Task<string> getUserAsync(int userId) {
            return base.Channel.getUserAsync(userId);
        }
        
        public string getUserName(string userName) {
            return base.Channel.getUserName(userName);
        }
        
        public System.Threading.Tasks.Task<string> getUserNameAsync(string userName) {
            return base.Channel.getUserNameAsync(userName);
        }
        
        public string getUserEmail(string userEmail) {
            return base.Channel.getUserEmail(userEmail);
        }
        
        public System.Threading.Tasks.Task<string> getUserEmailAsync(string userEmail) {
            return base.Channel.getUserEmailAsync(userEmail);
        }
        
        public System.DateTime getDateofB(System.DateTime dateofB) {
            return base.Channel.getDateofB(dateofB);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> getDateofBAsync(System.DateTime dateofB) {
            return base.Channel.getDateofBAsync(dateofB);
        }
        
        public string getContact(string ContactNum) {
            return base.Channel.getContact(ContactNum);
        }
        
        public System.Threading.Tasks.Task<string> getContactAsync(string ContactNum) {
            return base.Channel.getContactAsync(ContactNum);
        }
        
        public string setUser(string userName, string userEmai, System.DateTime dateofB, string ContactNum, bool pizza, bool past, bool papwor, bool other) {
            return base.Channel.setUser(userName, userEmai, dateofB, ContactNum, pizza, past, papwor, other);
        }
        
        public System.Threading.Tasks.Task<string> setUserAsync(string userName, string userEmai, System.DateTime dateofB, string ContactNum, bool pizza, bool past, bool papwor, bool other) {
            return base.Channel.setUserAsync(userName, userEmai, dateofB, ContactNum, pizza, past, papwor, other);
        }
    }
}
